### ISSUE TITLE
Imported yaml files can no longer refer to variables in the importing yaml

### ISSUE THREAD

**Issue by jsyrjala** [NitorCreations/nitor-deploy-tools#30]
This used to work, but since some recent ndt version started giving this error:

```
Referenced parameter "((bucket))" in file foo/bar/bucketpolicy.yaml not declared in template parameters in foo/bar/template.yaml
```
in template.yaml:

```
  myBucket:
    Type: AWS::S3::Bucket
     ...

  resInboxPolicy:
    'Fn::ImportYaml': bucketpolicy.yaml
    bucket: myBucket
```

bucketpolicy.yaml:
```
Type: "AWS::S3::BucketPolicy"
Properties:
  Bucket: {Ref: ((bucket))}
  PolicyDocument:
  ...
```
